# Generated by Django 4.2.9 on 2024-02-15 12:41

import django.core.validators
from django.db import migrations, models
import fruitipediaApp.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(validators=[django.core.validators.MaxLengthValidator(25), django.core.validators.MinLengthValidator(2), fruitipediaApp.profiles.validators.name_starts_with_letter])),
                ('last_name', models.CharField(validators=[django.core.validators.MaxLengthValidator(35), django.core.validators.MinLengthValidator(1), fruitipediaApp.profiles.validators.name_starts_with_letter])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('password', models.CharField(help_text='*Password length requirements: 8 to 20 characters', validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(8)])),
                ('image', models.URLField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
