# Generated by Django 4.2.6 on 2023-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_alter_fruit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
