# Generated by Django 4.2.6 on 2023-11-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_alter_fruit_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
