# Generated by Django 4.2.9 on 2024-02-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_alter_fruit_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
